# TODO Gorila DQN has more significant fitures
entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        'score': 3069,
        'stddev': 1093,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        'score': 739.5,
        'stddev': 3024,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        'score': 3359,
        'stddev': 775,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        'score': 6012,
        'stddev': 1744,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        'score': 1629,
        'stddev': 542,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        'score': 85641,
        'stddev': 17600,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        'score': 429.7,
        'stddev': 650,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        'score': 26300,
        'stddev': 7725,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        'score': 6846,
        'stddev': 1619,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        'score': 42.4,
        'stddev': 88,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        'score': 71.8,
        'stddev': 8.4,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        'score': 401.2,
        'stddev': 26.9,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        'score': 8309,
        'stddev': 5237,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        'score': 6687,
        'stddev': 2916,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        'score': 114103,
        'stddev': 22797,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        'score': 9711,
        'stddev': 2406,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        'score': -18.1,
        'stddev': 2.6,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        'score': 301.8,
        'stddev': 24.6,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        'score': -0.8,
        'stddev': 19.0,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        'score': 30.3,
        'stddev': 0.7,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        'score': 328.3,
        'stddev': 250.5,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        'score': 8520,
        'stddev': 3279,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        'score': 306.7,
        'stddev': 223.9,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        'score': 19950,
        'stddev': 158,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        'score': -1.6,
        'stddev': 2.5,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        'score': 576.7,
        'stddev': 175.5,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        'score': 6740,
        'stddev': 2959,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        'score': 3805,
        'stddev': 1033,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        'score': 23270,
        'stddev': 5955,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        'score': 2311,
        'stddev': 525,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        'score': 7257,
        'stddev': 547,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        'score': 18.9,
        'stddev': 1.3,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        'score': 1788,
        'stddev': 5473,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        'score': 10596,
        'stddev': 3294,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        'score': 8316,
        'stddev': 1049,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        'score': 18257,
        'stddev': 4268,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        'score': 51.6,
        'stddev': 4.7,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        'score': 5286,
        'stddev': 1310,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        'score': 1976,
        'stddev': 893,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        'score': 57997,
        'stddev': 3152,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        'score': -2.5,
        'stddev': 1.9,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        'score': 5947,
        'stddev': 1600,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        'score': 186.7,
        'stddev': 41.9,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        'score': 8456,
        'stddev': 3162,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        'score': 380.0,
        'stddev': 238.6,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        'score': 42684,
        'stddev': 16287,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        'score': 3393,
        'stddev': 2019,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        'score': 4977,
        'stddev': 1235,
    },
]
