human_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1033.4,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 169.1,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6060.8,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 16837.0,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1193.2,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 319688.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 886.0,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 24740.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 17417.2,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1011.1,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 69.6,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 73.5,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 368.9,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3853.5,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3495.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 113782.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 27510.0,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 69803.4,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -0.3,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1216.6,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3.2,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 28.8,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1448.1,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 15253.0,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 200.5,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 14892.5,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -2.5,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 573.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 11204.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6796.1,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 30207.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 42.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1241.3,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 8960.3,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 12366.5,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -186.7,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 19.1,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -575.5,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 11020.8,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 10838.4,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 43156.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 59.1,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 14498.0,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -11490.4,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 810.0,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 2628.7,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 58365.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1.9,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -7.8,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6608.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 92.2,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 19086.9,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 21.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 367823.7,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6201.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6270.6,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 8593.0,
    },
]

noop_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3747.7,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1793.3,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 5393.2,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 17356.5,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 734.7,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 106056.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1030.6,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 31700.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 13772.8,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1225.4,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 68.1,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 91.6,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 418.5,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 5409.4,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 5809.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 117282.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 35338.5,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 58044.2,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -5.5,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1211.8,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 15.5,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 33.3,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1683.3,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 14840.8,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 412.0,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 20130.2,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -2.7,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1358.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 12992.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 7920.5,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 29710.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 2711.4,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 10616.0,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 12252.5,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -29.9,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 20.9,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 129.7,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 15088.5,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 14884.5,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 44127.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 65.1,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 16452.7,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -9021.8,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3067.8,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 2525.5,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 60142.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -2.9,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -22.8,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 8339.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 218.4,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 22972.2,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 98.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 309941.9,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 7492.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 11712.6,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 10163.0,
    },
]

entries = human_entries + noop_entries
