entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 813.5,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 189.2,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1195.8,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3324.7,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 933.6,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 629166.5,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 399.4,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 19938.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3822.1,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 54.0,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 74.2,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 313.0,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 6296.9,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3191.8,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 65451.0,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 14880.1,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -11.3,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 71.0,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 4.6,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 10.2,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 426.6,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 4373.0,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 538.4,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 8963.4,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -1.7,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 444.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1431.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 6363.1,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 20620.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 84.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1263.0,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 9238.5,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 16.7,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 2598.6,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 7089.8,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 5310.3,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 43079.8,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 61.8,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 10145.9,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1183.3,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 14919.2,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -0.7,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 8267.8,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 118.5,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 8747.7,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 523.4,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 112093.4,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 10431.0,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 6159.4,
    },
]
