human_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 621.6,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 188.2,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 2774.3,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 5285.0,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1219.0,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 260556.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 469.8,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 25240.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 9107.9,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 635.8,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 62.3,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 52.1,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 338.7,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 5166.6,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 2483.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 94315.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 8531.0,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 13943.5,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -6.4,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 475.9,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -3.4,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 26.3,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 258.3,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 8742.8,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 170.0,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 15341.4,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -3.6,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 416.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6138.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6130.4,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 22771.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 30.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1401.8,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 7871.5,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 10364.0,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -432.9,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 17.7,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 346.3,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 10713.3,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6579.0,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 43884.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 52.0,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 4199.4,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -29404.3,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 2166.8,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1495.7,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 53052.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -7.6,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 11.0,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 5375.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 63.6,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 4721.1,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 75.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 148883.6,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 155.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 5439.5,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 7874.0,
    },
]

entries = human_entries
# NOOP entries from DQN2015
