# TODO No citation: where are these scores from?
human_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 634.0,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 178.4,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 3489.3,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 3170.5,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1458.7,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 292491.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 312.7,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 23750.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 9743.2,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 493.4,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 56.5,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 70.3,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 354.5,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 3973.9,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 5017.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 98128.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 15917.5,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 12550.7,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -6.0,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 626.7,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -1.6,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 26.9,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 496.1,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8190.4,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 298.0,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 14992.9,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -1.6,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 697.5,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4496.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 6206.0,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 20882.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 47.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1092.3,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 6738.8,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 7484.8,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -113.2,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 18.0,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 207.9,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 9271.5,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4748.5,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 35215.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 58.7,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4216.7,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -12142.1,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1295.4,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1293.8,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 52970.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -6.0,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 11.1,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4786.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 45.6,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8038.5,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 136.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 154414.1,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1609.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4577.5,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4412.0,
    },
]

# TODO No citation: where are these scores from?
noop_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1620.0,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 978.0,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4280.4,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4359.0,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1364.5,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 279987.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 455.0,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 29900.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8627.5,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 585.6,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 50.4,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 88.0,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 385.5,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4657.7,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 6126.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 110763.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 23633.0,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 12149.4,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -6.6,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 729.0,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -4.9,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 30.8,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 797.4,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8777.4,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 473.0,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 20437.8,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -1.9,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 768.5,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 7259.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8422.3,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 26059.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 3085.6,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8207.8,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8485.2,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -286.1,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 19.5,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 146.7,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 13117.3,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 7377.6,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 39544.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 63.9,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 5860.6,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -13062.3,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 3482.8,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1692.3,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 54282.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -5.6,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 12.2,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4870.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 68.1,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 9989.9,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 163.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 196760.4,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 2704.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 18098.9,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 5363.0,
    },
]

entries = human_entries + noop_entries
