entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        'score': 2404,
        'stddev': 242,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        'score': 924,
        'stddev': 159,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        'score': 3595,
        'stddev': 169,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        'score': 6253,
        'stddev': 154,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        'score': 1824,
        'stddev': 83,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        'score': 876000,
        'stddev': 15013,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        'score': 455,
        'stddev': 25,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        'score': 28981,
        'stddev': 1497,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        'score': 10564,
        'stddev': 613,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        'score': 634,
        'stddev': 16,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        'score': 62,
        'stddev': 4,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        'score': 87,
        'stddev': 1,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        'score': 396,
        'stddev': 13,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        'score': 6440,
        'stddev': 1194,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        'score': 7271,
        'stddev': 473,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        'score': 116480,
        'stddev': 896,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        'score': 18303,
        'stddev': 2611,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        'score': 12696,
        'stddev': 214,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        'score': -6,
        'stddev': 1,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        'score': 835,
        'stddev': 56,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        'score': 4,
        'stddev': 4,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        'score': 31,
        'stddev': 0,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        'score': 1000,
        'stddev': 258,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        'score': 11825,
        'stddev': 1444,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        'score': 366,
        'stddev': 26,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        'score': 15176,
        'stddev': 3870,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        'score': -2,
        'stddev': 0,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        'score': 909,
        'stddev': 223,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        'score': 8166,
        'stddev': 1512,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        'score': 8343,
        'stddev': 79,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        'score': 30444,
        'stddev': 1673,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        'score': 2,
        'stddev': 3,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        'score': 2674,
        'stddev': 43,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        'score': 8179,
        'stddev': 551,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        'score': 9704,
        'stddev': 2907,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        'score': 20,
        'stddev': 0,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        'score': 2361,
        'stddev': 781,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        'score': 11241,
        'stddev': 1579,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        'score': 7241,
        'stddev': 140,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        'score': 37910,
        'stddev': 1778,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        'score': 55,
        'stddev': 1,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        'score': 4163,
        'stddev': 425,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        'score': -12630,
        'stddev': 202,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        'score': 4055,
        'stddev': 842,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        'score': 1283,
        'stddev': 39,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        'score': 40934,
        'stddev': 3598,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        'score': -6,
        'stddev': 0,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        'score': 8,
        'stddev': 7,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        'score': 6167,
        'stddev': 73,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        'score': 218,
        'stddev': 1,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        'score': 11652,
        'stddev': 737,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        'score': 319,
        'stddev': 158,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        'score': 429936,
        'stddev': 71110,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        'score': 3601,
        'stddev': 873,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        'score': 20648,
        'stddev': 1543,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        'score': 4806,
        'stddev': 285,
    },
]
