human_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 128.30,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 11.80,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 166.90,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 164.50,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 871.30,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 13463.00,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 21.70,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3560.00,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 254.60,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 196.10,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 35.20,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -1.50,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1.60,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1925.50,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 644.00,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 9337.00,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1965.50,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 208.30,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -16.00,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -81.80,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -77.10,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 0.10,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 66.40,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 250.00,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 245.50,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1580.30,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -9.70,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 33.50,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 100.00,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1151.90,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 304.00,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 25.00,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 197.80,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1747.80,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1134.40,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -348.80,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -18.00,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 662.80,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 183.00,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 588.30,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 200.00,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 2.40,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 215.50,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -15287.40,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 2047.20,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 182.60,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 697.00,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -9.70,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -21.40,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3273.00,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 12.70,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 707.20,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 18.00,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 20452.0,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 804.00,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1476.90,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 475.00,
    },
]

noop_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 227.80,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 5.80,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 222.40,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 210.00,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 719.10,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 12850.00,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 14.20,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2360.00,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 363.90,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 23.10,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.10,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1.70,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2090.90,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 811.00,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 10780.50,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 152.10,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -18.60,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.00,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -91.70,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.00,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 65.20,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 257.60,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 173.00,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1027.00,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -11.20,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 29.00,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 52.00,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1598.00,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 258.50,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.00,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 307.30,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2292.30,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -20.70,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 24.90,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 163.90,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1338.50,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 11.50,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2.20,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 68.40,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 148.00,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 664.00,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -23.80,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 3568.00,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 11.40,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 533.40,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.00,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 16256.90,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 563.50,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 32.50,
    },
]

entries = human_entries + noop_entries
