human_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1334.7,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 129.1,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 6548.9,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 22484.5,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1745.1,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 330647.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 876.6,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 25520.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 31181.3,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 865.9,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 52.0,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 72.3,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 343.0,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 3489.1,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 4635.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 127512.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 23666.5,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 61277.5,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 16.0,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1831.0,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 9.8,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 28.9,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 3510.0,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 34858.8,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 269.5,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 20889.9,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -0.2,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 3961.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 12185.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 6872.8,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 31676.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 51.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1865.9,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 10497.6,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 16903.6,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -427.0,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 18.9,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 670.7,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 9944.0,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 11807.2,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 52264.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 56.2,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 25463.7,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -10169.1,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 2272.8,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 3912.1,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 61582.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 5.9,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -5.3,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 5963.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 56.9,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 12157.4,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 94.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 295972.8,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 5727.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 4687.4,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 9474.0,
    },
]

# TODO No citation: where are the scores from?
noop_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4203.8,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1838.9,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 7672.1,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 31527.0,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 2654.3,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 357324.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1054.6,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 31530.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 23384.2,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1305.6,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 47.9,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 95.6,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 373.9,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4463.2,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8600.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 141161.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 31286.5,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 71846.4,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 18.5,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 2093.0,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 39.5,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 33.7,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4380.1,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 32487.2,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 548.5,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 23037.7,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 1.3,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 5148.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 16200.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 9728.0,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 39581.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 6518.7,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 12270.5,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 18992.7,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -356.5,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 20.6,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 200.0,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 16256.5,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 14522.3,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 57608.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 62.6,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 26357.8,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': -9996.9,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4309.0,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 2865.8,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 63302.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 8.9,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 9197.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 204.6,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 16154.1,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 54.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 282007.3,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 4802.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 11357.0,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        "score-source-title": "Dueling Network Architectures for Deep Reinforcement Learning",
        'score': 10469.0,
    },
]

entries = human_entries + noop_entries
