entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        'score': 2403,
        'stddev': 78,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        'score': 1610,
        'stddev': 228,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        'score': 5510,
        'stddev': 483,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        'score': 14328,
        'stddev': 2859,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        'score': 3455,
        'stddev': 1054,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        'score': 923733,
        'stddev': 25798,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        'score': 1068,
        'stddev': 277,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        'score': 36786,
        'stddev': 2892,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        'score': 20793,
        'stddev': 284,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        'score': 905,
        'stddev': 21,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        'score': 71,
        'stddev': 26,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        'score': 89,
        'stddev': 4,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        'score': 516,
        'stddev': 26,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        'score': 4269,
        'stddev': 261,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        'score': 8893,
        'stddev': 871,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        'score': 118305,
        'stddev': 7796,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        'score': 20525,
        'stddev': 3114,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        'score': 36150,
        'stddev': 4646,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        'score': 1,
        'stddev': 0,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        'score': 1240,
        'stddev': 83,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        'score': 11,
        'stddev': 2,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        'score': 32,
        'stddev': 0,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        'score': 753,
        'stddev': 101,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        'score': 14574,
        'stddev': 1837,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        'score': 447,
        'stddev': 94,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        'score': 6246,
        'stddev': 2092,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        'score': -3,
        'stddev': 0,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        'score': 1235,
        'stddev': 421,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        'score': 10944,
        'stddev': 4149,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        'score': 8805,
        'stddev': 313,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        'score': 36310,
        'stddev': 5093,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        'score': 3,
        'stddev': 4,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        'score': 2722,
        'stddev': 148,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        'score': 8181,
        'stddev': 742,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        'score': 16028,
        'stddev': 3317,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        'score': 21,
        'stddev': 0,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        'score': 3712,
        'stddev': 161,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        'score': 15545,
        'stddev': 462,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        'score': 9425,
        'stddev': 705,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        'score': 45993,
        'stddev': 2709,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        'score': 51,
        'stddev': 5,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        'score': 2282,
        'stddev': 361,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        'score': -14763,
        'stddev': 706,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        'score': 6088,
        'stddev': 1791,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        'score': 2186,
        'stddev': 92,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        'score': 47133,
        'stddev': 7016,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        'score': -1,
        'stddev': 2,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        'score': 7035,
        'stddev': 908,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        'score': 232,
        'stddev': 34,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        'score': 14255,
        'stddev': 1658,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        'score': 97,
        'stddev': 76,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        'score': 322507,
        'stddev': 135629,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        'score': 9198,
        'stddev': 4364,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        'score': 23915,
        'stddev': 13939,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        'score': 6920,
        'stddev': 4567,
    },
]
