entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 939.2,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 103.4,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 628,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 987.3,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 907.3,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 62687,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 190.8,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 15820,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 929.4,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 43.9,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 44,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 5.2,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 8803,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 1582,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 23411,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 520.5,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': -13.1,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 129.1,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': -89.5,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 19.1,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 216.9,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 1288,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 387.7,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 6459,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': -9.5,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 202.8,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 1622,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 3372,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 19544,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 10.7,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 1692,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 2500,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': -19,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 684.3,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 613.5,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 1904,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 67.7,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 28.7,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 664.8,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 250.1,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 1070,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': -0.1,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 3741,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 114.3,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 3533,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 66,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 16871,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 1981,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level control through deep reinforcement learning",
        'score': 3365,
    },
]
