entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        'score': 2027,
        'stddev': 92,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        'score': 904,
        'stddev': 125,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        'score': 2879,
        'stddev': 293,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        'score': 6822,
        'stddev': 181,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        'score': 2544,
        'stddev': 523,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        'score': 422700,
        'stddev': 4759,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        'score': 1296,
        'stddev': 20,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        'score': 16411,
        'stddev': 1283,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        'score': 9214,
        'stddev': 608,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        'score': 1022,
        'stddev': 151,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        'score': 37,
        'stddev': 2,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        'score': 91,
        'stddev': 1,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        'score': 496,
        'stddev': 56,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        'score': 5350,
        'stddev': 432,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        'score': 5285,
        'stddev': 159,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        'score': 134783,
        'stddev': 5495,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        'score': 52917,
        'stddev': 3355,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        'score': 37085,
        'stddev': 803,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        'score': 3,
        'stddev': 1,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        'score': -7,
        'stddev': 30,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        'score': 288,
        'stddev': 20,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        'score': 7992,
        'stddev': 672,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        'score': 379,
        'stddev': 31,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        'score': 30791,
        'stddev': 246,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        'score': -2,
        'stddev': 0,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        'score': 509,
        'stddev': 34,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        'score': 1166,
        'stddev': 76,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        'score': 9422,
        'stddev': 980,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        'score': 37422,
        'stddev': 2202,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        'score': 14,
        'stddev': 12,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        'score': 2436,
        'stddev': 249,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        'score': 7168,
        'stddev': 224,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        'score': 9476,
        'stddev': 569,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        'score': 7,
        'stddev': 19,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        'score': 3781,
        'stddev': 2994,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        'score': 18586,
        'stddev': 574,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        'score': 8135,
        'stddev': 483,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        'score': 45315,
        'stddev': 1837,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        'score': 6,
        'stddev': 0,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        'score': 1744,
        'stddev': 0,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        'score': -12972,
        'stddev': 2846,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        'score': 12380,
        'stddev': 519,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        'score': 1034,
        'stddev': 49,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        'score': 49156,
        'stddev': 3882,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        'score': -8,
        'stddev': 1,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        'score': -6,
        'stddev': 9,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        'score': 10294,
        'stddev': 1449,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        'score': 213,
        'stddev': 14,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        'score': 89067,
        'stddev': 12635,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        'score': 229402,
        'stddev': 153801,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        'score': 8953,
        'stddev': 1377,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        'score': 21596,
        'stddev': 1917,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        'score': 16544,
        'stddev': 1513,
    },
]
