entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 227.8,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 5.8,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 222.4,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 210.0,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 719.1,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 12850.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 14.2,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2360.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 363.9,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 23.1,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.1,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1.7,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2090.9,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 811.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 10780.5,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 152.1,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -18.6,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -91.7,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 65.2,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 257.6,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 173.0,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1027.0,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -11.2,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 29.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 52.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1598.0,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 258.5,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 307.3,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2292.3,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -20.7,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 24.9,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 163.9,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1338.5,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 11.5,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2.2,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 68.4,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 148.0,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 664.0,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -23.8,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 3568.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 11.4,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 533.4,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 0.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 16256.9,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 563.5,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 32.5,
    },
]
