entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1033.4,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 169.1,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6060.8,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 16837.0,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1193.2,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 319688.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 886.0,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 24740.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 17417.2,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1011.1,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 69.6,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 73.5,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 368.9,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3853.5,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3495.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 113782.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 27510.0,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 69803.4,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -0.3,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1216.6,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 3.2,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 28.8,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1448.1,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 15253.0,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 200.5,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 14892.5,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -2.5,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 573.0,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 11204.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6796.1,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 30207.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 42.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1241.3,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 8960.3,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 12366.5,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -186.7,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 19.1,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -575.5,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 11020.8,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 10838.4,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 43156.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 59.1,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 14498.0,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -11490.4,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 810.0,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 2628.7,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 58365.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 1.9,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': -7.8,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6608.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 92.2,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 19086.9,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 21.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 367823.7,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6201.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 6270.6,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Deep Reinforcement Learning with Double Q-learning",
        'score': 8593.0,
    },
]
