entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        'score': 5778,
        'stddev': 2189,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        'score': 3537,
        'stddev': 521,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        'score': 11231,
        'stddev': 503,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        'score': 28350,
        'stddev': 607,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        'score': 86700,
        'stddev': 80459,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        'score': 972175,
        'stddev': 31961,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        'score': 1318,
        'stddev': 37,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        'score': 52262,
        'stddev': 1480,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        'score': 18501,
        'stddev': 662,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        'score': 1896,
        'stddev': 604,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        'score': 68,
        'stddev': 6,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        'score': 100,
        'stddev': 0,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        'score': 263,
        'stddev': 20,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        'score': 7596,
        'stddev': 1134,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        'score': 11477,
        'stddev': 1299,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        'score': 171171,
        'stddev': 2095,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        'score': 42253,
        'stddev': 2142,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        'score': 69311,
        'stddev': 26289,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        'score': 1,
        'stddev': 0,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        'score': 2013,
        'stddev': 219,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        'score': 57,
        'stddev': 2,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        'score': 34,
        'stddev': 0,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        'score': 2923,
        'stddev': 1519,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        'score': 38909,
        'stddev': 2229,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        'score': 2209,
        'stddev': 99,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        'score': 31533,
        'stddev': 4970,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        'score': 3,
        'stddev': 1,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        'score': 4682,
        'stddev': 2281,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        'score': 15227,
        'stddev': 243,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        'score': 10754,
        'stddev': 181,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        'score': 41672,
        'stddev': 1668,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        'score': 57,
        'stddev': 15,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        'score': 5546,
        'stddev': 367,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        'score': 12211,
        'stddev': 251,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        'score': 10379,
        'stddev': 547,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        'score': 21,
        'stddev': 0,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        'score': 279,
        'stddev': 109,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        'score': 27121,
        'stddev': 422,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        'score': 23134,
        'stddev': 1434,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        'score': 234352,
        'stddev': 132671,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        'score': 64,
        'stddev': 1,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        'score': 16754,
        'stddev': 6619,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        'score': -7550,
        'stddev': 451,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        'score': 6522,
        'stddev': 750,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        'score': 5909,
        'stddev': 1318,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        'score': 75867,
        'stddev': 8623,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        'score': 10,
        'stddev': 0,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        'score': 17301,
        'stddev': 1200,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        'score': 269,
        'stddev': 19,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        'score': 61326,
        'stddev': 6052,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        'score': 815,
        'stddev': 114,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        'score': 870954,
        'stddev': 135363,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        'score': 9149,
        'stddev': 641,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        'score': 86101,
        'stddev': 4136,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        'score': 14874,
        'stddev': 214,
    },
]
