entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        'score': 1899,
        'stddev': 111,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        'score': 491,
        'stddev': 485,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        'score': 3060,
        'stddev': 101,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        'score': 32478,
        'stddev': 2567,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        'score': 4541,
        'stddev': 311,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        'score': 465700,
        'stddev': 4224,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        'score': 1033,
        'stddev': 463,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        'score': 17871,
        'stddev': 5007,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        'score': 11237,
        'stddev': 1582,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        'score': 1235,
        'stddev': 259,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        'score': 42,
        'stddev': 11,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        'score': 100,
        'stddev': 0,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        'score': 374,
        'stddev': 27,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        'score': 8282,
        'stddev': 685,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        'score': 7561,
        'stddev': 1190,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        'score': 139950,
        'stddev': 18190,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        'score': 55492,
        'stddev': 3844,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        'score': 37880,
        'stddev': 2093,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        'score': 3,
        'stddev': 1,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        'score': 300,
        'stddev': 424,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        'score': -38,
        'stddev': 39,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        'score': 18,
        'stddev': 13,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        'score': 261,
        'stddev': 0,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        'score': 12439,
        'stddev': 16229,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        'score': 314,
        'stddev': 25,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        'score': 8471,
        'stddev': 4332,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        'score': -3,
        'stddev': 1,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        'score': 188,
        'stddev': 103,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        'score': 1604,
        'stddev': 278,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        'score': 22849,
        'stddev': 12175,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        'score': 55790,
        'stddev': 23886,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        'score': 4,
        'stddev': 3,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        'score': 3401,
        'stddev': 761,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        'score': 8798,
        'stddev': 1847,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        'score': 50338,
        'stddev': 30396,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        'score': 12,
        'stddev': 11,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        'score': 100,
        'stddev': 0,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        'score': 17896,
        'stddev': 1522,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        'score': 7878,
        'stddev': 162,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        'score': 30454,
        'stddev': 13309,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        'score': 36,
        'stddev': 3,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        'score': 943,
        'stddev': 41,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        'score': -15970,
        'stddev': 9887,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        'score': 10427,
        'stddev': 3878,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        'score': 1126,
        'stddev': 154,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        'score': 45008,
        'stddev': 11570,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        'score': 1,
        'stddev': 1,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        'score': 11124,
        'stddev': 1753,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        'score': 164,
        'stddev': 49,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        'score': 103557,
        'stddev': 51492,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        'score': 294724,
        'stddev': 140514,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        'score': 12723,
        'stddev': 3420,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        'score': 61755,
        'stddev': 4798,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        'score': 1324,
        'stddev': 1715,
    },
]
