human_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 813.54,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 189.15,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1195.85,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3324.70,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 933.63,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 629166.50,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 399.42,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 19938.00,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3822.07,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 53.95,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 74.20,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 313.03,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 6296.87,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3191.75,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 65451.00,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 14880.13,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -11.35,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 71.04,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 4.64,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 10.16,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 426.60,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 4373.04,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 538.37,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 8963.36,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -1.72,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 444.00,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1431.00,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 6363.09,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 20620.00,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 84.00,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1263.05,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 9238.50,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 16.71,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 2598.55,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 7089.83,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 5310.27,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 43079.80,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 61.78,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 10145.85,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1183.29,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 14919.25,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -0.69,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 8267.80,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 118.45,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 8747.67,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 523.40,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 112093.37,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 10431.00,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 6159.40,
    },
]

noop_entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2620.53,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1189.70,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1450.41,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 6433.33,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1047.66,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 100069.16,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 609.00,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 25266.66,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 3302.91,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 54.01,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 94.88,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 402.20,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 8432.30,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 4167.50,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 85919.16,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 13693.12,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -10.62,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 114.90,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 20.19,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 11.69,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 605.16,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 5279.00,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1054.58,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 14913.87,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': -0.61,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 605.00,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 2549.16,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 7882.00,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 27543.33,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 4.16,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 3233.50,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 6182.16,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 18.30,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 748.60,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 10815.55,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 8344.83,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 51007.99,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 36.43,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 13169.06,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1883.41,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 19144.99,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 10.87,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 10659.33,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 244.97,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 12561.58,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 1245.33,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 157550.21,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 13731.33,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        "score-source-title": "Human-level Control through Deep Reinforcement Learning",
        'score': 7129.33,
    },
]

entries = human_entries + noop_entries
