entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 570.2,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 133.4,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3332.3,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 124.5,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 697.1,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 76108.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 176.3,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 17560.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 8672.4,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 41.2,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 25.8,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 303.9,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3773.1,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3046.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 50992.0,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 12835.2,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -21.6,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 475.6,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -2.3,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 25.8,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 157.4,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 2731.8,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 216.5,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 12952.5,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -3.8,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 348.5,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 2696.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3864.0,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 11875.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 50.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 763.5,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 5439.9,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 16.2,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 298.2,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 4589.8,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 4065.3,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 9264.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 58.5,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 2793.9,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 1449.7,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 34081.0,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': -2.3,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 5640.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 32.4,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 3311.3,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 54.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 20228.1,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 246.0,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Massively Parallel Methods for Deep Reinforcement Learning",
        'score': 831.0,
    },
]
