entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'No-op start',
        'score': 6163,
        'stddev': 1077,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'No-op start',
        'score': 2296,
        'stddev': 154,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'No-op start',
        'score': 8010,
        'stddev': 381,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'No-op start',
        'score': 11170,
        'stddev': 5355,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'No-op start',
        'score': 2220,
        'stddev': 91,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'No-op start',
        'score': 902742,
        'stddev': 17087,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'No-op start',
        'score': 1428,
        'stddev': 37,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'No-op start',
        'score': 40481,
        'stddev': 2161,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'No-op start',
        'score': 16298,
        'stddev': 1101,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'No-op start',
        'score': 1122,
        'stddev': 35,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'No-op start',
        'score': 72,
        'stddev': 6,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'No-op start',
        'score': 99,
        'stddev': 0,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'No-op start',
        'score': 200,
        'stddev': 21,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'No-op start',
        'score': 4166,
        'stddev': 23,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'No-op start',
        'score': 7388,
        'stddev': 1024,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'No-op start',
        'score': 163335,
        'stddev': 2460,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'No-op start',
        'score': 37275,
        'stddev': 1572,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'No-op start',
        'score': 61033,
        'stddev': 9707,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'No-op start',
        'score': 17,
        'stddev': 7,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'No-op start',
        'score': 2064,
        'stddev': 81,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'No-op start',
        'score': 35,
        'stddev': 5,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'No-op start',
        'score': 34,
        'stddev': 0,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'No-op start',
        'score': 2807,
        'stddev': 1457,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'No-op start',
        'score': 27313,
        'stddev': 2629,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'No-op start',
        'score': 1682,
        'stddev': 170,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'No-op start',
        'score': 35895,
        'stddev': 1035,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'No-op start',
        'score': -0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'No-op start',
        'score': 1667,
        'stddev': 134,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'No-op start',
        'score': 14847,
        'stddev': 29,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'No-op start',
        'score': 10733,
        'stddev': 65,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'No-op start',
        'score': 30316,
        'stddev': 2397,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'No-op start',
        'score': 3650,
        'stddev': 445,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'No-op start',
        'score': 9919,
        'stddev': 38,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'No-op start',
        'score': 8215,
        'stddev': 403,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'No-op start',
        'score': 21,
        'stddev': 0,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'No-op start',
        'score': 227,
        'stddev': 138,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'No-op start',
        'score': 19819,
        'stddev': 2640,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'No-op start',
        'score': 18405,
        'stddev': 93,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'No-op start',
        'score': 64051,
        'stddev': 1106,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'No-op start',
        'score': 63,
        'stddev': 1,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'No-op start',
        'score': 19595,
        'stddev': 1493,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'No-op start',
        'score': -7989,
        'stddev': 1349,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'No-op start',
        'score': 3423,
        'stddev': 152,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'No-op start',
        'score': 1158,
        'stddev': 74,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'No-op start',
        'score': 70264,
        'stddev': 2147,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'No-op start',
        'score': 1,
        'stddev': 3,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'No-op start',
        'score': 0,
        'stddev': 0,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'No-op start',
        'score': 14094,
        'stddev': 652,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'No-op start',
        'score': 280,
        'stddev': 8,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'No-op start',
        'score': 93931,
        'stddev': 56045,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'No-op start',
        'score': 1433,
        'stddev': 10,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'No-op start',
        'score': 876503,
        'stddev': 61496,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'No-op start',
        'score': 6534,
        'stddev': 882,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'No-op start',
        'score': 43120,
        'stddev': 21466,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'No-op start',
        'score': 13959,
        'stddev': 613,
    },
]
