entries = [
    {
        'env-title': 'atari-alien',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1191.0,
    },
    {
        'env-title': 'atari-amidar',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 98.9,
    },
    {
        'env-title': 'atari-assault',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 3081.3,
    },
    {
        'env-title': 'atari-asterix',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 9199.5,
    },
    {
        'env-title': 'atari-asteroids',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1677.2,
    },
    {
        'env-title': 'atari-atlantis',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 207526.0,
    },
    {
        'env-title': 'atari-bank-heist',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 823.7,
    },
    {
        'env-title': 'atari-battle-zone',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 22250.0,
    },
    {
        'env-title': 'atari-beam-rider',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 12041.9,
    },
    {
        'env-title': 'atari-berzerk',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 644.0,
    },
    {
        'env-title': 'atari-bowling',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 58.0,
    },
    {
        'env-title': 'atari-boxing',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 69.6,
    },
    {
        'env-title': 'atari-breakout',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 481.1,
    },
    {
        'env-title': 'atari-centipede',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 2959.4,
    },
    {
        'env-title': 'atari-chopper-command',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 6685.0,
    },
    {
        'env-title': 'atari-crazy-climber',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 109337.0,
    },
    {
        'env-title': 'atari-defender',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 20634.0,
    },
    {
        'env-title': 'atari-demon-attack',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 19478.8,
    },
    {
        'env-title': 'atari-double-dunk',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -5.3,
    },
    {
        'env-title': 'atari-enduro',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1265.6,
    },
    {
        'env-title': 'atari-fishing-derby',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 3.5,
    },
    {
        'env-title': 'atari-freeway',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 28.4,
    },
    {
        'env-title': 'atari-frostbite',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 288.7,
    },
    {
        'env-title': 'atari-gopher',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 17478.2,
    },
    {
        'env-title': 'atari-gravitar',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 351.0,
    },
    {
        'env-title': 'atari-hero',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 15150.9,
    },
    {
        'env-title': 'atari-ice-hockey',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -3.8,
    },
    {
        'env-title': 'atari-jamesbond',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1074.5,
    },
    {
        'env-title': 'atari-kangaroo',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 9053.0,
    },
    {
        'env-title': 'atari-krull',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 11209.5,
    },
    {
        'env-title': 'atari-kung-fu-master',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 20181.0,
    },
    {
        'env-title': 'atari-montezuma-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 44.0,
    },
    {
        'env-title': 'atari-ms-pacman',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 964.7,
    },
    {
        'env-title': 'atari-name-this-game',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 8738.5,
    },
    {
        'env-title': 'atari-phoenix',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 16107.8,
    },
    {
        'env-title': 'atari-pitfall',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -193.7,
    },
    {
        'env-title': 'atari-pong',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 18.7,
    },
    {
        'env-title': 'atari-private-eye',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 2202.3,
    },
    {
        'env-title': 'atari-qbert',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 12740.5,
    },
    {
        'env-title': 'atari-riverraid',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 10205.5,
    },
    {
        'env-title': 'atari-road-runner',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 57207.0,
    },
    {
        'env-title': 'atari-robotank',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 51.3,
    },
    {
        'env-title': 'atari-seaquest',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 11848.8,
    },
    {
        'env-title': 'atari-skiing',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -29404.3,
    },
    {
        'env-title': 'atari-solaris',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 134.6,
    },
    {
        'env-title': 'atari-space-invaders',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 1696.9,
    },
    {
        'env-title': 'atari-star-gunner',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 58946.0,
    },
    {
        'env-title': 'atari-surround',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -5.3,
    },
    {
        'env-title': 'atari-tennis',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': -2.3,
    },
    {
        'env-title': 'atari-time-pilot',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 5391.0,
    },
    {
        'env-title': 'atari-tutankham',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 96.5,
    },
    {
        'env-title': 'atari-up-n-down',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 16626.5,
    },
    {
        'env-title': 'atari-venture',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 110.0,
    },
    {
        'env-title': 'atari-video-pinball',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 214925.3,
    },
    {
        'env-title': 'atari-wizard-of-wor',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 2755.0,
    },
    {
        'env-title': 'atari-yars-revenge',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 6626.7,
    },
    {
        'env-title': 'atari-zaxxon',
        'env-variant': 'Human start',
        "score-source-title": "Prioritized Experience Replay",
        'score': 5901.0,
    },
]
